### ISSUE TITLE
Need a channel thumbnail

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/sushi-chef-goalkicker-tech-books#5]
Here is a screenshot that could be used:
![todo generate thumbnail from this](https://user-images.githubusercontent.com/163966/51857777-1d002900-2301-11e9-9a78-08be160c9c6b.png)

Maybe lighten + blur then add `Goalkicker tech books` in a big font in the middle?

@markmlearneq if you have image editing skills I'll let you do it, else assign this one to me and I'll try to come up with a channel thumbnail in the right format: https://github.com/learningequality/ricecooker/blob/master/docs/nodes.md#thumbnails

**Comment by dragondave** [comment]
Done.
